version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-app
    ports:
      - "${APP_PORT}:9090"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_AT_EXPIRE: ${JWT_AT_EXPIRE}
      JWT_RT_EXPIRE: ${JWT_RT_EXPIRE}

      # Redis
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: bookstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: bookstore-redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  mysql_data:
